package kr.ac.sejong.gotgan.BackEndAPI

const val userIdStr : String = "user_id"
const val userPwStr : String = "user_pw"
const val sessionStr : String = "session"
const val userUuidStr : String = "user_uuid"
const val productsStr : String = "products"
const val productIndexStr : String = "product_index"
const val productBarcodeStr : String = "product_barcode"
const val productCreatedStr : String = "product_created"
const val productNameStr : String = "product_name"
const val productStatusStr : String = "product_status"
const val productOwnerStr : String = "product_owner"
const val productOwnerNameStr : String = "product_owner_name"
const val productGroupStr : String = "product_group"
const val productGroupNameStr : String = "product_group_name"
const val productGroupRentableStr : String = "product_group_rentable"
const val productGroupPriorityStr : String = "product_group_priority"
const val rentIndexStr : String = "rent_index"
const val rentUserStr : String = "rent_user"
const val rentUserIndexStr : String = "rent_user_index"
const val rentUserNameStr : String = "rent_user_name"
const val rentProductStr : String = "rent_product"
const val rentStatusStr : String = "rent_status"
const val rentDelayedStr : String = "rent_delayed"
const val rentTimeStartStr : String = "rent_time_start"
const val rentTimeEndStr : String = "rent_time_end"
const val rentTimeReturnStr : String = "rent_time_return"
const val rentProductNameStr : String = "rent_product_name"
const val and : String = "&"
const val assignment : String = "="

const val rentUserIdStr : String = "rent_user_id"
const val rentProductIndexStr : String = "rent_product_index"
const val rentProductGroupIndexStr : String = "rent_product_group_index"
const val rentProductGroupNameStr : String = "rent_product_group_name"
const val rentProductBarcodeStr : String = "rent_product_barcode"